language: scala
jdk: openjdk8
before_install:
  - git fetch --tags
script: ./sbt -batch ++${TRAVIS_SCALA_VERSION} test
cache:
  directories:
  - $HOME/.cache
  - $HOME/.ivy2/cache
  - $HOME/.sbt
stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)
jobs:
  include:
    - scala: 2.11.12
    - scala: 2.12.10
    - stage: release
      script: ./sbt ci-release
